### ISSUE TITLE
能支持win7吗？

### ISSUE THREAD

**Issue by admin05** [cataerogong/STRapp#2]
win7下运行strapp出错了

**Comment by cataerogong** [comment]
应该是因为我用的 Python 3.10，等我试一下 3.8，不过我没有Win7，也不知道Win7下的浏览器支持 易笺 如何

**Comment by cataerogong** [comment]
我用 Python 3.8 重新打包了一下，[strapp_v1.0.0_py38_x64_for_win7.zip](https://github.com/cataerogong/STRapp/releases/download/v1.0.0/strapp_v1.0.0_py38_x64_for_win7.zip)，你看看 Win7 能运行吗？

**Comment by admin05** [comment]
win7下可以了，非常感谢！
